# Generated by Django 4.1 on 2022-09-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWEB', '0003_persona_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='año',
            new_name='anio',
        ),
        migrations.AddField(
            model_name='auto',
            name='region',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
