# Generated by Django 4.1 on 2022-09-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_rename_contraseña_usuario_apodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(max_length=15),
        ),
    ]
