# Generated by Django 4.1 on 2022-09-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_alter_usuario_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(max_length=50),
        ),
    ]
