# Generated by Django 4.1 on 2022-10-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_alter_usuario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='usuario',
        ),
    ]
