# Generated by Django 4.1 on 2022-09-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_usuario_codigo_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('apodo', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=50)),
            ],
        ),
    ]
