# Generated by Django 4.1 on 2022-10-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='owner',
            field=models.IntegerField(blank=True, default=1, verbose_name='Dueño datos'),
        ),
    ]
