# Generated by Django 4.1 on 2022-09-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_usuario_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario_2',
        ),
    ]
