# Generated by Django 4.1 on 2022-10-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_usuario_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
    ]
