# Generated by Django 4.1 on 2022-09-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_delete_usuario_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=50)),
                ('contenido', models.TextField(max_length=50)),
                ('orden', models.CharField(max_length=50)),
            ],
        ),
    ]
