# Generated by Django 4.1 on 2022-10-20 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0008_remove_usuario_owner_remove_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='owner',
            field=models.IntegerField(blank=True, default=1, verbose_name='Dueño datos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
