# Generated by Django 4.1 on 2022-10-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_usuario_owner_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='DAVID_AESTETIC.png', null=True, upload_to='avatares'),
        ),
    ]
