# Generated by Django 4.1 on 2022-10-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default=1, null=True, upload_to='avatares'),
        ),
    ]
