# Generated by Django 4.1 on 2022-10-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0011_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default=models.URLField(verbose_name='DAVID_AESTETIC.png'), null=True, upload_to='avatares'),
        ),
    ]
