# Generated by Django 4.1 on 2022-10-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_alter_postmodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
